#!/bin/bash

CURRDIR=$(cd "$(dirname "$0")";pwd)
PROJECTDIR=$(dirname "${CURRDIR}")
PATH="${PATH}:${PROJECTDIR}/bin"

for i in `seq 0 32`
do
	NAME="redis${i}"
	DIR="${CURRDIR}/${NAME}"
	if [ -d ${DIR} ]; then
		PORT=$(($i + 6379))
		redis-cli -p ${PORT} shutdown
	fi
done
